# Generated by Django 5.2.12 on 2026-03-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=150)),
                ('class_name', models.CharField(max_length=150)),
                ('course_name', models.CharField(max_length=150)),
                ('members', models.TextField(help_text='Satu anggota per baris')),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('primary_color', models.CharField(default='#0f766e', max_length=7)),
                ('secondary_color', models.CharField(default='#f1f5f9', max_length=7)),
                ('font_family', models.CharField(choices=[('Arial, sans-serif', 'Arial'), ("'Courier New', monospace", 'Courier New'), ('Georgia, serif', 'Georgia'), ("'Trebuchet MS', sans-serif", 'Trebuchet MS'), ('Verdana, sans-serif', 'Verdana')], default='Arial, sans-serif', max_length=50)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
