# Generated by Django 5.2.12 on 2026-03-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteappearance',
            name='theme_preset',
            field=models.CharField(choices=[('midnight', 'Midnight Tech'), ('sunrise', 'Sunrise Clay'), ('forest', 'Forest Mist'), ('royal', 'Royal Violet'), ('mono', 'Monochrome Clean')], default='midnight', max_length=30),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='font_family',
            field=models.CharField(choices=[('Manrope, sans-serif', 'Manrope'), ('Poppins, sans-serif', 'Poppins'), ("'Nunito Sans', sans-serif", 'Nunito Sans'), ("'Space Grotesk', sans-serif", 'Space Grotesk'), ('Merriweather, serif', 'Merriweather'), ('Arial, sans-serif', 'Arial'), ("'Courier New', monospace", 'Courier New'), ('Georgia, serif', 'Georgia'), ("'Trebuchet MS', sans-serif", 'Trebuchet MS'), ('Verdana, sans-serif', 'Verdana')], default='Manrope, sans-serif', max_length=50),
        ),
    ]
